name: .NET Core Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
      working-directory: SampleLibrary
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: SampleLibrary
    # - name: Install code coverage tools
    #   run: choco install opencover.portable\
    #    choco install codecov
    - name: Test
      run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=xml
      working-directory: SampleLibrary
    - name: Publish code coverage reports to codecove.io
      uses: codecov/codecov-action@v1
      working-directory: SampleLibrary
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        fail_ci_if_error: true
